apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPAllowedUsers
metadata:
  name: psp-pods-allowed-user-ranges
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    runAsUser:
      rule: MustRunAs 
      ranges:
        - min: 100
          max: 65535
    runAsGroup:
      rule: MustRunAs 
      ranges:
        - min: 100
          max: 65535
    supplementalGroups:
      rule: MustRunAs  
      ranges:
        - min: 100
          max: 65535
    fsGroup:
      rule: MustRunAs 
      ranges:
        - min: 100
          max: 65535
